// eslint-disable-next-line import/prefer-default-export
export const mockData = {
  allPropositions: {},
  wobject: {},
  currentProposition: [],
  discardProposition: jest.fn(),
  assignPropositionHandler: jest.fn(),
  intl: {},
  goToProducts: jest.fn(),
  match: {},
  history: {},
  user: {},
  userName: 'asd09',
  loadingAssignDiscard: false,
  isAssign: false,
  isCatalogWrap: true,
  catalogGetMenuList: jest.fn(),
  catalogHandleSortChange: jest.fn(),
  catalogSort: 'recency',
  isGetNested: false,
};

export const defaultPropositionProps = {
  allPropositions: {},
  wobject: {},
  currentProposition: [],
  discardProposition: jest.fn(),
  assignPropositionHandler: jest.fn(),
  intl: {},
  goToProducts: jest.fn(),
  match: {},
  history: {},
  user: {},
  userName: 'asd09',
  loadingAssignDiscard: false,
  isAssign: false,
  isCatalogWrap: true,
  catalogGetMenuList: jest.fn(),
  catalogHandleSortChange: jest.fn(),
  catalogSort: 'recency',
  isGetNested: false,
  maxReward: 1,
  minReward: 1,
  rewardPrise: '',
  rewardMax: '',
};
