export const HOURS = {
  Minute: 1,
  Minute5: 5,
  Minute15: 15,
  Minute30: 30,
  Hour: 60,
  Hour4: 60 * 4,
  Hour8: 60 * 8,
  Day: 60 * 24,
  Week: 60 * 24 * 7,
  Month: 60 * 24 * 31,
  MINUTE: 1,
  MINUTE5: 5,
  MINUTE15: 15,
  MINUTE30: 30,
  HOUR: 60,
  HOUR4: 60 * 4,
  HOUR8: 60 * 8,
  DAY: 60 * 24,
  WEEK: 60 * 24 * 7,
  MONTH: 60 * 24 * 31,
};

export const CMD = {
  getTime: 'get_time',
  getUserAccount: 'get_user_account',
  getUserSettings: 'get_user_settings',
  getUserStatistics: 'get_user_statistics',
  getUserRates: 'get_user_rates',
  getFavorites: 'get_favorites',
  addFavorites: 'add_favorites',
  delFavorites: 'del_favorites',
  getClosedDeals: 'get_closed_deals',
  getOpenDeals: 'get_open_deals',
  sendOpenMarketOrder: 'send_open_market_order',
  sendCloseMarketOrder: 'send_close_market_order',
  changeAccount: 'change_account',
  duplicateOpenDeal: 'duplicate_open_deal',
  changeOpenDeal: 'change_open_deal',
  getLimitStopOrders: 'get_limit_stop_orders',
  getChartData: 'get_chart_data',
  openMarketOrderRejected: 'open_market_order_rejected',
};
