version: '3.7'

services:
  main:
    container_name: waivio-frontend
    build:
      context: .
      args:
        ENV: $NODE_ENV
    command: yarn start $NODE_ENV
    restart: always
    network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    env_file:
      - ./env/$NODE_ENV.env
