import Loadable from 'react-loadable';
import Loading from '../client/components/Icon/Loading';

const loableComponent = url =>
  Loadable({
    loader: () => import(url),
    loading: Loading,
  });

export default {
  Bookmarks: loableComponent('../client/bookmarks/Bookmarks'),
  Drafts: loableComponent('../client/post/Write/Drafts'),
  Replies: loableComponent('../client/replies/Replies'),
  Activity: loableComponent('../client/activity/Activity'),
  Wallet: loableComponent('../client/wallet/Wallet'),
  BusyEditor: loableComponent('../client/post/Write/Write'),
  Editor: loableComponent('../client/post/EditPost/EditPost'),
  Settings: loableComponent('../client/settings/Settings'),
  GuestsSettings: loableComponent('../client/settings/GuestsSettings'),
  NotificationSettings: loableComponent('../client/settings/NotificationSettings'),
  ProfileSettings: loableComponent('../client/settings/ProfileSettings'),
  Invite: loableComponent('../client/invite/Invite'),
  User: loableComponent('../client/user/User'),
  Wobj: loableComponent('../client/object/Wobj'),
  UserProfile: loableComponent('../client/user/UserProfile'),
  UserComments: loableComponent('../client/user/UserComments'),
  UserFollowers: loableComponent('../client/user/UserFollowers'),
  UserFollowing: loableComponent('../client/user/UserFollowing'),
  UserReblogs: loableComponent('../client/user/UserReblogs'),
  UserWallet: loableComponent('../client/user/UserWallet'),
  WalletTable: loableComponent('../client/wallet/WalletTable'),
  UserActivity: loableComponent('../client/activity/UserActivity'),
  Discover: loableComponent('../client/discover/Discover'),
  Objects: loableComponent('../client/objects/Objects'),
  Search: loableComponent('../client/search/Search'),
  Notifications: loableComponent('../client/notifications/Notifications'),
  RewardsList: loableComponent('../client/rewards/RewardsList/RewardsList'),
  Error404: loableComponent('../client/statics/Error404'),
  ExitPage: loableComponent('../client/statics/ExitPage'),
  ObjectPageFeed: loableComponent('../client/object/ObjectFeed'),
  ObjectFeed: loableComponent('../client/object/ObjectFeed/ObjectFeed'),
  WobjFollowers: loableComponent('../client/object/WobjFollowers'),
  ObjectGallery: loableComponent('../client/object/ObjectGallery/ObjectGallery'),
  ObjectGalleryAlbum: loableComponent('../client/object/ObjectGallery/ObjectGalleryAlbum'),
  WobjHistory: loableComponent('../client/object/WobjHistory'),
  ObjectAbout: loableComponent('../client/object/ObjectAbout'),
  CatalogWrap: loableComponent('../client/object/Catalog/CatalogWrap'),
  WobjExpertise: loableComponent('../client/object/WobjExpertise'),
  UserExpertise: loableComponent('../client/user/UserExpertise'),
  DiscoverObjects: loableComponent('../client/discoverObjects/DiscoverObjects'),
  Rewards: loableComponent('../client/rewards/Rewards'),
  CreateRewardForm: loableComponent('../client/rewards/Create-Edit/CreateRewardForm'),
  ManageCampaign: loableComponent('../client/rewards/Manage/Manage'),
  MatchBotCampaign: loableComponent('../client/rewards/MatchBot/MatchBot'),
  ReceivablesCampaign: loableComponent('../client/rewards/Receivables/Receivables'),
  PayablesCampaign: loableComponent('../client/rewards/Payables/Payables'),
  BlacklistCampaign: loableComponent('../client/rewards/Blacklist/Blacklist'),
  Reports: loableComponent('../client/rewards/Reports/Reports'),
  PaymentCampaign: loableComponent('../client/rewards/Payment/Payment'),
  ObjectOfTypePage: loableComponent('../client/object/ObjectOfTypePage/ObjectOfTypePage'),
  SubFeed: loableComponent('../client/feed/SubFeed'),
  UserInfo: loableComponent('../client/app/Sidebar/UserInfo'),
  ConfirmationModal: loableComponent('../client/widgets/ConfirmationModal'),
  RewardsComponent: loableComponent('../client/rewards/RewardsComponent/RewardsComponent'),
  HistoryCampaign: loableComponent('../client/rewards/History/History'),
};
