import path from '../routes/pathConfig.json';
import URL from '../../src/common/constants/routing';

export default {
  Bookmarks: path.bookmarks,
  Drafts: path.drafts,
  Replies: path.replies,
  Activity: path.activity,
  Wallet: path.wallet,
  Editor: path.editor,
  Edit: path.edit,
  Settings: path.settings,
  EditProfile: path.editProfile,
  Invite: path.invite,
  GuestsSettings: path.guestsSettings,
  NotificationSettings: path.notificationSettings,
  DiscoverObjects: `${path.discoverObjects}${path.params.typeName}?`,
  Discover: `${path.discover}${path.params.search}`,
  Objects: path.object,
  Post: `${path.params.category}?${path.params.author}${path.params.permlink}${path.params.original}?`,
  Exit: path.exit,
  Search: path.search,
  PaymentCampaignPayables: `${path.rewards}${path.payables}${path.userName}${path.params.reservationPermlink}?`,
  PaymentCampaignReceivables: `${path.rewards}${path.receivables}${path.userName}${path.params.reservationPermlink}?`,
  MatchBotCampaign: `${path.rewards}${path.matchBot}`,
  RewardsHistory: `${path.rewards}${path.history}`,
  RewardsGuideHistory: `${path.rewards}${path.guideHistory}`,
  RewardsMessage: `${path.rewards}${path.messages}`,
  BlacklistCampaign: `${path.rewards}${path.blacklist}${path.params.listType}?`,
  CreateRewardFormDetails: `${path.rewards}${path.details}${path.params.campaignId}`,
  CreateRewardFormDublicate: `${path.rewards}${path.createDuplicate}${path.params.campaignId}`,
  RewardsComponent: `${path.rewards}${path.params.filterKey}${path.params.campaignParent}?`,
  ManageCampaign: `${path.rewards}${path.manage}`,
  ReceivablesCampaign: `${path.rewards}${path.receivables}`,
  PayablesCampaign: `${path.rewards}${path.payables}`,
  Reports: `${path.rewards}${path.reports}`,
  UserProfile: path.params.account,
  UserComments: `${path.params.account}${path.comments}`,
  UserFollowers: `${path.params.account}${path.followers}`,
  UserFollowing: `${path.params.account}${path.following}`,
  UserReblogs: `${path.params.account}${path.reblogs}`,
  UserWallet: `${path.params.account}${path.transfers}`,
  UserActivity: `${path.params.account}${path.activity}`,
  UserExpertise: `${path.params.account}${path.expertise}`,
  UserInfo: `${path.params.account}${path.about}`,
  ObjectPageFeed: `${path.object}${path.params.name}`,
  ObjectAbout: `${path.object}${path.params.name}${path.about}`,
  WobjFollowers: `${path.object}${path.params.name}${path.followers}`,
  ObjectGallery: `${path.object}${path.params.name}${path.gallery}`,
  WobjExpertise: `${path.object}${path.params.name}${path.expertise}`,
  ObjectGalleryAlbum: `${path.object}${path.params.name}${path.gallery}${path.album}${path.params.itemId}`,
  WobjHistory: `${path.object}${path.params.name}${path.updates}(${URL.WOBJ.params[1]})?`,
  CatalogWrap: `${path.object}${path.params.name}(${path.list}|${path.menu})`,
  ObjectOfTypePage: `${path.object}${path.params.name}${path.page}`,
  ConfirmationModal: `${path.confirmation}`,
  Notifications: `${path.notificationSettings}`,
};
