import path from '../routes/pathConfig.json';
import URL from '../../src/common/constants/routing';

export default {
  Bookmarks: path.bookmarks,
  Drafts: path.drafts,
  Replies: path.replies,
  Activity: path.activity,
  Wallet: path.wallet,
  Editor: path.editor,
  Edit: path.edit,
  Settings: path.settings,
  EditProfile: path.editProfile,
  Invite: path.invite,
  GuestsSettings: path.guestsSettings,
  NotificationSettings: path.notificationSettings,
  DiscoverObjects: `${path.discoverObjects}${path.params.typeName}?`,
  Discover: `${path.discover}${path.params.search}`,
  Objects: path.objects,
  Post: `${path.params.category}?${path.params.postAuthor}${path.params.permlink}${path.params.original}?`,
  Exit: path.exit,
  Search: path.search,
  PaymentCampaignPayables: `${path.payables}${path.userName}${path.params.reservationPermlink}?`,
  PaymentCampaignReceivables: `${path.receivables}${path.userName}${path.params.reservationPermlink}?`,
  MatchBotCampaign: `${path.matchBot}`,
  RewardsHistory: `${path.history}`,
  RewardsGuideHistory: `${path.guideHistory}`,
  RewardsMessage: `${path.messages}`,
  BlacklistCampaign: `${path.blacklist}${path.params.listType}?`,
  CreateRewardFormDetails: `${path.details}${path.params.campaignId}`,
  CreateRewardFormDublicate: `${path.createDuplicate}${path.params.campaignId}`,
  RewardsComponent: `${path.params.filterKey}${path.params.campaignParent}?`,
  ManageCampaign: path.manage,
  ReceivablesCampaign: path.receivables,
  PayablesCampaign: path.payables,
  Reports: path.reports,
  UserProfile: path.params.account,
  UserComments: `${path.comments}`,
  UserFollowers: `${path.followers}`,
  UserFollowing: `${path.following}`,
  UserReblogs: `${path.reblogs}`,
  UserWallet: `${path.transfers}`,
  UserActivity: `${path.activity}`,
  UserExpertise: `${path.expertise}`,
  UserInfo: `${path.about}`,
  ObjectPageFeed: `${path.object}${path.params.name}`,
  ObjectAbout: `${path.about}`,
  WobjFollowers: `${path.followers}`,
  ObjectGallery: `${path.gallery}`,
  WobjExpertise: `${path.expertise}`,
  ObjectGalleryAlbum: `${path.gallery}${path.album}${path.params.itemId}`,
  WobjHistory: `${path.updates}(${URL.WOBJ.params[1]})?`,
  CatalogWrap: `/(${path.list}|${path.menu})`,
  ObjectOfTypePage: `${path.page}`,
  ConfirmationModal: `${path.confirmation}`,
  Notifications: `${path.notificationSettings}`,
};
