// // eslint-disable-next-line import/prefer-default-export
// export const MOCK_DATA_RESPONSE_GET_OBJECT = {
//   albums_count: 1,
//   app: 'waiviodev/1.0.0',
//   author: 'vmn31',
//   author_permlink: 'kpg-3r76a6-kings-menu',
//   authority: {},
//   bell: false,
//   children: [],
//   community: '',
//   count_posts: 0,
//   createdAt: '2020-08-06T11:25:34.501Z',
//   creator: 'bxy_walle',
//   defaultShowLink: '/object/kpg-3r76a6-kings-menu/list',
//   default_name: 'Kings menu',
//   description: 'Perfect menu',
//   exposedFields: [],
//   fields: [],
//   followers_count: 0,
//   galleryAlbum: [],
//   is_extending_open: true,
//   is_posting_open: true,
//   last_posts_count: 0,
//   last_posts_counts_by_hours: [
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//     0,
//   ],
//   latest_posts: [],
//   listItem: [],
//   listItems: [],
//   name: 'Kings menu',
//   object_type: 'list',
//   parent: {},
//   photos_count: 0,
//   preview_gallery: [],
//   sortCustom: [],
//   updatedAt: '2020-10-22T07:00:36.069Z',
//   weight: 0,
//   youFollows: false,
//   __v: 0,
//   _id: '5f2be8ae7aaee47d45e611f5',
// };
