// eslint-disable-next-line import/prefer-default-export
export const MOCK_GET_NESTED_WOBJECT = {
  __v: 0,
  _id: '5f50f8eb1cce890625fcff32',
  albums_count: 0,
  app: 'waiviodev/1.0.0',
  author: 'xcv47',
  author_permlink: 'ajx-2b6pzi-pizza',
  authority: {},
  bell: false,
  children: [],
  community: '',
  count_posts: 0,
  createdAt: '2020-09-03T14:08:43.163Z',
  creator: 'waivio_mariia-osadcha',
  defaultShowLink: '/object/ajx-2b6pzi-pizza/list',
  default_name: 'pizza',
  exposedFields: [
    'status',
    'avatar',
    'authority',
    'name',
    'title',
    'background',
    'parent',
    'tagCategory',
    'categoryItem',
    'galleryAlbum',
    'galleryItem',
    'website',
    'description',
    'listItem',
    'sortCustom',
  ],
  fields: [],
  followers_count: 0,
  is_extending_open: true,
  is_posting_open: true,
  last_posts_count: 0,
  last_posts_counts_by_hours: [],
  latest_posts: [],
  listItem: [],
  listItems: [],
  name: 'pizza',
  object_type: 'list',
  parent: {},
  photos_count: 0,
  preview_gallery: [],
  sortCustom: [],
  updatedAt: '2020-10-20T11:00:33.374Z',
  weight: 0,
  youFollows: false,
};
