export const SampleWObject = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ce40dbe8ca3d04633808c0e',
      creator: 'alexeygrigurko',
      author: 'an98r',
      name: 'newsFilter',
      body: 'blog',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectInRowDataWithSameWeigth = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectInRowDataWithDifferentWeigth = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectNotInRowDataWithSameWeigth = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectNotInRowDataWithDifferentWeigth = {
  fields: [
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },

    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectMoreTwoObjInRowDataWithSameWeigth = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alex',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'someList',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectMoreTwoObjInRowDataWithDifferentWeigth = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },
    {
      weight: 3,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'sometext',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
  ],
};

export const wObjectMoreTwoObjNotInRowDataWithSameWeigth = {
  fields: [
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allow',
    },
  ],
};

export const wObjectMoreTwoObjNotInRowDataWithDifferentWeigth = {
  fields: [
    {
      weight: 2,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allowList',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5cdac71a59847a4fc774aa59',
      creator: 'suy38',
      author: 'suy38',
      name: 'name',
      body: 'milk',
    },
    {
      weight: 1,
      locale: 'en-US',
      _id: '5ce40b868ca3d0463374943a',
      creator: 'alexeygrigurko',
      author: 'b23df',
      name: 'newsFilter',
      body: 'steem',
    },

    {
      weight: 2,
      locale: 'en-US',
      _id: '5ced27d7be601c180c285782',
      creator: 'alexeygrigurko',
      author: 'j5gs7',
      name: 'website',
      body: 'http://www.broadwaychinese.ca',
    },
    {
      weight: 4,
      locale: 'en-US',
      _id: '5ce40ca08ca3d046337a8300',
      creator: 'alexeygrigurko',
      author: 'vp4g5',
      name: 'newsFilter',
      body: 'allow',
    },
  ],
};
