const timezones = [
  { label: '(GMT+02:00) Europe/Andorra', value: 'Europe/Andorra' },
  { label: '(GMT+04:00) Asia/Dubai', value: 'Asia/Dubai' },
  { label: '(GMT+04:30) Asia/Kabul', value: 'Asia/Kabul' },
  { label: '(GMT+02:00) Europe/Tirane', value: 'Europe/Tirane' },
  { label: '(GMT+04:00) Asia/Yerevan', value: 'Asia/Yerevan' },
  { label: '(GMT+08:00) Antarctica/Casey', value: 'Antarctica/Casey' },
  { label: '(GMT+07:00) Antarctica/Davis', value: 'Antarctica/Davis' },
  { label: '(GMT+10:00) Antarctica/DumontDUrville', value: 'Antarctica/DumontDUrville' },
  { label: '(GMT+05:00) Antarctica/Mawson', value: 'Antarctica/Mawson' },
  { label: '(GMT-03:00) Antarctica/Palmer', value: 'Antarctica/Palmer' },
  { label: '(GMT-03:00) Antarctica/Rothera', value: 'Antarctica/Rothera' },
  { label: '(GMT+03:00) Antarctica/Syowa', value: 'Antarctica/Syowa' },
  { label: '(GMT+02:00) Antarctica/Troll', value: 'Antarctica/Troll' },
  { label: '(GMT+05:00) Antarctica/Vostok', value: 'Antarctica/Vostok' },
  { label: '(GMT-03:00) America/Argentina/Buenos_Aires', value: 'America/Argentina/Buenos_Aires' },
  { label: '(GMT-03:00) America/Argentina/Cordoba', value: 'America/Argentina/Cordoba' },
  { label: '(GMT-03:00) America/Argentina/Salta', value: 'America/Argentina/Salta' },
  { label: '(GMT-03:00) America/Argentina/Jujuy', value: 'America/Argentina/Jujuy' },
  { label: '(GMT-03:00) America/Argentina/Tucuman', value: 'America/Argentina/Tucuman' },
  { label: '(GMT-03:00) America/Argentina/Catamarca', value: 'America/Argentina/Catamarca' },
  { label: '(GMT-03:00) America/Argentina/La_Rioja', value: 'America/Argentina/La_Rioja' },
  { label: '(GMT-03:00) America/Argentina/San_Juan', value: 'America/Argentina/San_Juan' },
  { label: '(GMT-03:00) America/Argentina/Mendoza', value: 'America/Argentina/Mendoza' },
  { label: '(GMT-03:00) America/Argentina/San_Luis', value: 'America/Argentina/San_Luis' },
  { label: '(GMT-03:00) America/Argentina/Rio_Gallegos', value: 'America/Argentina/Rio_Gallegos' },
  { label: '(GMT-03:00) America/Argentina/Ushuaia', value: 'America/Argentina/Ushuaia' },
  { label: '(GMT-11:00) Pacific/Pago_Pago', value: 'Pacific/Pago_Pago' },
  { label: '(GMT+02:00) Europe/Vienna', value: 'Europe/Vienna' },
  { label: '(GMT+10:30) Australia/Lord_Howe', value: 'Australia/Lord_Howe' },
  { label: '(GMT+10:00) Antarctica/Macquarie', value: 'Antarctica/Macquarie' },
  { label: '(GMT+10:00) Australia/Hobart', value: 'Australia/Hobart' },
  { label: '(GMT+10:00) Australia/Currie', value: 'Australia/Currie' },
  { label: '(GMT+10:00) Australia/Melbourne', value: 'Australia/Melbourne' },
  { label: '(GMT+10:00) Australia/Sydney', value: 'Australia/Sydney' },
  { label: '(GMT+09:30) Australia/Broken_Hill', value: 'Australia/Broken_Hill' },
  { label: '(GMT+10:00) Australia/Brisbane', value: 'Australia/Brisbane' },
  { label: '(GMT+10:00) Australia/Lindeman', value: 'Australia/Lindeman' },
  { label: '(GMT+09:30) Australia/Adelaide', value: 'Australia/Adelaide' },
  { label: '(GMT+09:30) Australia/Darwin', value: 'Australia/Darwin' },
  { label: '(GMT+08:00) Australia/Perth', value: 'Australia/Perth' },
  { label: '(GMT+08:45) Australia/Eucla', value: 'Australia/Eucla' },
  { label: '(GMT+04:00) Asia/Baku', value: 'Asia/Baku' },
];

export default timezones;
