const timezones = [
  { label: '(GMT-12:00) International Date Line West', value: 'Etc/GMT+12' },
  { label: '(GMT-11:00) Midway Island, Samoa', value: 'Pacific/Midway' },
  { label: '(GMT-10:00) Hawaii', value: 'Pacific/Honolulu' },
  { label: '(GMT-09:00) Alaska', value: 'America/Anchorage' },
  { label: '(GMT-08:00) Pacific Time (US & Canada)', value: 'America/Los_Angeles' },
  { label: '(GMT-07:00) Mountain Time (US & Canada)', value: 'America/Denver' },
  { label: '(GMT-06:00) Central Time (US & Canada)', value: 'America/Chicago' },
  { label: '(GMT-05:00) Eastern Time (US & Canada)', value: 'America/New_York' },
  { label: '(GMT-04:00) Atlantic Time (Canada)', value: 'America/Halifax' },
  { label: '(GMT-03:00) Buenos Aires, Greenland', value: 'America/Argentina/Buenos_Aires' },
  { label: '(GMT-02:00) Mid-Atlantic', value: 'America/Noronha' },
  { label: '(GMT-01:00) Azores, Cape Verde Is.', value: 'Atlantic/Azores' },
  { label: '(GMT+00:00) London, Lisbon, Casablanca', value: 'Europe/London' },
  { label: '(GMT+01:00) Amsterdam, Berlin, Rome, Paris', value: 'Europe/Berlin' },
  { label: '(GMT+02:00) Athens, Bucharest, Istanbul', value: 'Europe/Athens' },
  { label: '(GMT+03:00) Moscow, St. Petersburg, Nairobi', value: 'Europe/Moscow' },
  { label: '(GMT+03:30) Tehran', value: 'Asia/Tehran' },
  { label: '(GMT+04:00) Abu Dhabi, Muscat', value: 'Asia/Dubai' },
  { label: '(GMT+04:30) Kabul', value: 'Asia/Kabul' },
  { label: '(GMT+05:00) Islamabad, Karachi', value: 'Asia/Karachi' },
  { label: '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi', value: 'Asia/Kolkata' },
  { label: '(GMT+05:45) Kathmandu', value: 'Asia/Kathmandu' },
  { label: '(GMT+06:00) Almaty, Astana, Dhaka', value: 'Asia/Dhaka' },
  { label: '(GMT+06:30) Yangon (Rangoon)', value: 'Asia/Yangon' },
  { label: '(GMT+07:00) Bangkok, Hanoi, Jakarta', value: 'Asia/Bangkok' },
  { label: '(GMT+08:00) Beijing, Hong Kong, Singapore', value: 'Asia/Shanghai' },
  { label: '(GMT+09:00) Tokyo, Seoul, Osaka', value: 'Asia/Tokyo' },
  { label: '(GMT+09:30) Adelaide, Darwin', value: 'Australia/Adelaide' },
  { label: '(GMT+10:00) Sydney, Guam', value: 'Australia/Sydney' },
  { label: '(GMT+11:00) Magadan, Solomon Is., New Caledonia', value: 'Pacific/Noumea' },
  { label: '(GMT+12:00) Auckland, Fiji', value: 'Pacific/Auckland' },
  { label: "(GMT+13:00) Nuku'alofa", value: 'Pacific/Tongatapu' },
];

export default timezones;
