const timezones = [
  { label: '(GMT-11:00) Midway, United States Minor Outlying Islands', value: 'Pacific/Midway' },
  { label: '(GMT-11:00) Niue, Niue', value: 'Pacific/Niue' },
  { label: '(GMT-11:00) Pago Pago, American Samoa', value: 'Pacific/Pago_Pago' },
  { label: '(GMT-10:00) Hawaii, United States', value: 'Pacific/Honolulu' },
  { label: '(GMT-10:00) Rarotonga, Cook Islands', value: 'Pacific/Rarotonga' },
  { label: '(GMT-10:00) Tahiti, French Polynesia', value: 'Pacific/Tahiti' },
  { label: '(GMT-09:30) Marquesas, French Polynesia', value: 'Pacific/Marquesas' },
  { label: '(GMT-09:00) Gambier, French Polynesia', value: 'Pacific/Gambier' },
  { label: '(GMT-09:00) Anchorage, United States', value: 'America/Anchorage' },
  { label: '(GMT-08:00) Pitcairn, Pitcairn Islands', value: 'Pacific/Pitcairn' },
  { label: '(GMT-08:00) Los Angeles, United States', value: 'America/Los_Angeles' },
  { label: '(GMT-08:00) Tijuana, Mexico', value: 'America/Tijuana' },
  { label: '(GMT-08:00) Vancouver, Canada', value: 'America/Vancouver' },
  { label: '(GMT-07:00) Boise, United States', value: 'America/Boise' },
  { label: '(GMT-06:00) Chihuahua, Mexico', value: 'America/Chihuahua' },
  { label: '(GMT-07:00) Creston, Canada', value: 'America/Creston' },
  { label: '(GMT-07:00) Dawson Creek, Canada', value: 'America/Dawson_Creek' },
  { label: '(GMT-07:00) Denver, United States', value: 'America/Denver' },
  { label: '(GMT-07:00) Edmonton, Canada', value: 'America/Edmonton' },
  { label: '(GMT-07:00) Hermosillo, Mexico', value: 'America/Hermosillo' },
  { label: '(GMT-07:00) Phoenix, United States', value: 'America/Phoenix' },
  { label: '(GMT-07:00) Whitehorse, Canada', value: 'America/Whitehorse' },
  { label: '(GMT-07:00) Yellowknife, Canada', value: 'America/Yellowknife' },
  { label: '(GMT-06:00) Belize, Belize', value: 'America/Belize' },
  { label: '(GMT-06:00) Central Time (Canada), Canada', value: 'America/Winnipeg' },
  { label: '(GMT-06:00) Central Time (US), United States', value: 'America/Chicago' },
  { label: '(GMT-06:00) Costa Rica, Costa Rica', value: 'America/Costa_Rica' },
  { label: '(GMT-06:00) El Salvador, El Salvador', value: 'America/El_Salvador' },
  { label: '(GMT-06:00) Galapagos, Ecuador', value: 'Pacific/Galapagos' },
  { label: '(GMT-06:00) Guatemala, Guatemala', value: 'America/Guatemala' },
  { label: '(GMT-06:00) Managua, Nicaragua', value: 'America/Managua' },
  { label: '(GMT-07:00) Mazatlan, Mexico', value: 'America/Mazatlan' },
  { label: '(GMT-06:00) Mexico City, Mexico', value: 'America/Mexico_City' },
  { label: '(GMT-06:00) Regina, Canada', value: 'America/Regina' },
  { label: '(GMT-06:00) Swift Current, Canada', value: 'America/Swift_Current' },
  { label: '(GMT-06:00) Tegucigalpa, Honduras', value: 'America/Tegucigalpa' },
  { label: '(GMT-06:00) Winnipeg, Canada', value: 'America/Winnipeg' },
  { label: '(GMT-05:00) Atikokan, Canada', value: 'America/Atikokan' },
  { label: '(GMT-05:00) Bogota, Colombia', value: 'America/Bogota' },
  { label: '(GMT-05:00) Cancun, Mexico', value: 'America/Cancun' },
  { label: '(GMT-05:00) Cayman, Cayman Islands', value: 'America/Cayman' },
  { label: '(GMT-05:00) Coral Harbour, Canada', value: 'America/Coral_Harbour' },
  { label: '(GMT-05:00) Detroit, United States', value: 'America/Detroit' },
  { label: '(GMT-05:00) Havana, Cuba', value: 'America/Havana' },
  { label: '(GMT-05:00) Indianapolis, United States', value: 'America/Indiana/Indianapolis' },
  { label: '(GMT-05:00) Iqaluit, Canada', value: 'America/Iqaluit' },
  { label: '(GMT-05:00) Jamaica, Jamaica', value: 'America/Jamaica' },
  { label: '(GMT-05:00) Lima, Peru', value: 'America/Lima' },
  { label: '(GMT-05:00) Montreal, Canada', value: 'America/Toronto' },
  { label: '(GMT-05:00) Nassau, Bahamas', value: 'America/Nassau' },
  { label: '(GMT-05:00) New York, United States', value: 'America/New_York' },
  { label: '(GMT-05:00) Panama, Panama', value: 'America/Panama' },
  { label: '(GMT-05:00) Port-au-Prince, Haiti', value: 'America/Port-au-Prince' },
  { label: '(GMT-04:00) Port of Spain, Trinidad and Tobago', value: 'America/Port_of_Spain' },
  { label: '(GMT-05:00) Rio Branco, Brazil', value: 'America/Rio_Branco' },
  { label: '(GMT-05:00) Toronto, Canada', value: 'America/Toronto' },
  { label: '(GMT-05:00) Washington DC, United States', value: 'America/New_York' },
  { label: '(GMT-04:00) Asuncion, Paraguay', value: 'America/Asuncion' },
  { label: '(GMT-04:00) Barbados, Barbados', value: 'America/Barbados' },
  { label: '(GMT-04:00) Blanc-Sablon, Canada', value: 'America/Blanc-Sablon' },
  { label: '(GMT-04:00) Boa Vista, Brazil', value: 'America/Boa_Vista' },
  { label: '(GMT-04:00) Campo Grande, Brazil', value: 'America/Campo_Grande' },
  { label: '(GMT-04:00) Caracas, Venezuela', value: 'America/Caracas' },
  { label: '(GMT-04:00) Cuiaba, Brazil', value: 'America/Cuiaba' },
  { label: '(GMT-04:00) Curacao, Curaçao', value: 'America/Curacao' },
  { label: '(GMT-05:00) Grand Turk, Turks and Caicos', value: 'America/Grand_Turk' },
  { label: '(GMT-04:00) Guadeloupe, Guadeloupe', value: 'America/Guadeloupe' },
  { label: '(GMT-04:00) Guyana, Guyana', value: 'America/Guyana' },
  { label: '(GMT-04:00) Halifax, Canada', value: 'America/Halifax' },
  { label: '(GMT-02:00) Godthab, Greenland', value: 'America/Nuuk' },
  { label: '(GMT-04:00) La Paz, Bolivia', value: 'America/La_Paz' },
  { label: '(GMT-04:00) Manaus, Brazil', value: 'America/Manaus' },
  { label: '(GMT-04:00) Martinique, Martinique', value: 'America/Martinique' },
  { label: '(GMT-04:00) Puerto Rico, United States', value: 'America/Puerto_Rico' },
  { label: '(GMT-04:00) Santiago, Chile', value: 'America/Santiago' },
  { label: '(GMT-04:00) Santo Domingo, Dominican Republic', value: 'America/Santo_Domingo' },
  { label: '(GMT-03:30) St. John’s, Canada', value: 'America/St_Johns' },
  { label: '(GMT-03:30) Newfoundland, Canada', value: 'America/St_Johns' },
  { label: '(GMT-04:00) Thule, Greenland', value: 'America/Thule' },
  { label: '(GMT-04:00) Tortola, British Virgin Islands', value: 'America/Tortola' },
  { label: '(GMT-04:00) Virgin Islands, United States', value: 'America/St_Thomas' },
  { label: '(GMT-03:00) Araguaina, Brazil', value: 'America/Araguaina' },
  { label: '(GMT-03:00) Bahia, Brazil', value: 'America/Bahia' },
  { label: '(GMT-03:00) Belem, Brazil', value: 'America/Belem' },
  { label: '(GMT-03:00) Buenos Aires, Argentina', value: 'America/Argentina/Buenos_Aires' },
  { label: '(GMT-03:00) Catamarca, Argentina', value: 'America/Argentina/Catamarca' },
  { label: '(GMT-03:00) Cayenne, French Guiana', value: 'America/Cayenne' },
  { label: '(GMT-03:00) Cordoba, Argentina', value: 'America/Argentina/Cordoba' },
  { label: '(GMT-03:00) Fortaleza, Brazil', value: 'America/Fortaleza' },
  { label: '(GMT-03:00) Jujuy, Argentina', value: 'America/Argentina/Jujuy' },
  { label: '(GMT-03:00) Maceio, Brazil', value: 'America/Maceio' },
  { label: '(GMT-03:00) Mendoza, Argentina', value: 'America/Argentina/Mendoza' },
  { label: '(GMT-03:00) Montevideo, Uruguay', value: 'America/Montevideo' },
  { label: '(GMT-03:00) Palmer, Antarctica', value: 'Antarctica/Palmer' },
  { label: '(GMT-03:00) Paramaribo, Suriname', value: 'America/Paramaribo' },
  { label: '(GMT-03:00) Punta Arenas, Chile', value: 'America/Punta_Arenas' },
  { label: '(GMT-03:00) Rio Gallegos, Argentina', value: 'America/Argentina/Rio_Gallegos' },
  { label: '(GMT-03:00) Rosario, Argentina', value: 'America/Argentina/Cordoba' },
  { label: '(GMT-03:00) Salvador, Brazil', value: 'America/Bahia' },
  { label: '(GMT-03:00) Sao Paulo, Brazil', value: 'America/Sao_Paulo' },
  { label: '(GMT-03:00) Stanley, Falkland Islands', value: 'Atlantic/Stanley' },
  { label: '(GMT-04:00) Tobago, Trinidad and Tobago', value: 'America/Port_of_Spain' },
  { label: '(GMT-02:00) Fernando de Noronha, Brazil', value: 'America/Noronha' },
  {
    label: '(GMT-02:00) South Georgia, South Georgia & South Sandwich Is.',
    value: 'Atlantic/South_Georgia',
  },
  { label: '(GMT-01:00) Azores, Portugal', value: 'Atlantic/Azores' },
  { label: '(GMT-01:00) Cape Verde, Cabo Verde', value: 'Atlantic/Cape_Verde' },
  { label: '(GMT-02:00) Scoresbysund, Greenland', value: 'America/Scoresbysund' },
  { label: '(GMT+00:00) Abidjan, Côte d’Ivoire', value: 'Africa/Abidjan' },
  { label: '(GMT+00:00) Accra, Ghana', value: 'Africa/Accra' },
  { label: '(GMT+00:00) Bissau, Guinea-Bissau', value: 'Africa/Bissau' },
  { label: '(GMT+00:00) Canary Islands, Spain', value: 'Atlantic/Canary' },
  { label: '(GMT+01:00) Casablanca, Morocco', value: 'Africa/Casablanca' },
  { label: '(GMT+00:00) Dakar, Senegal', value: 'Africa/Dakar' },
  { label: '(GMT+00:00) Dublin, Ireland', value: 'Europe/Dublin' },
  { label: '(GMT+00:00) Edinburgh, United Kingdom', value: 'Europe/London' },
  { label: '(GMT+00:00) Faroe, Faroe Islands', value: 'Atlantic/Faroe' },
  { label: '(GMT+00:00) GMT (no offset), Etc/UTC', value: 'Etc/UTC' },
  { label: '(GMT+00:00) Lisbon, Portugal', value: 'Europe/Lisbon' },
  { label: '(GMT+00:00) London, United Kingdom', value: 'Europe/London' },
  { label: '(GMT+00:00) Monrovia, Liberia', value: 'Africa/Monrovia' },
  { label: '(GMT+00:00) Reykjavik, Iceland', value: 'Atlantic/Reykjavik' },
  { label: '(GMT+00:00) Sao Tome, São Tomé & Príncipe', value: 'Africa/Sao_Tome' },
  { label: '(GMT+00:00) St Helena, St Helena', value: 'Atlantic/St_Helena' },
  { label: '(GMT+01:00) Algiers, Algeria', value: 'Africa/Algiers' },
  { label: '(GMT+01:00) Amsterdam, Netherlands', value: 'Europe/Amsterdam' },
  { label: '(GMT+01:00) Andorra, Andorra', value: 'Europe/Andorra' },
  { label: '(GMT+01:00) Barcelona, Spain', value: 'Europe/Madrid' },
  { label: '(GMT+01:00) Berlin, Germany', value: 'Europe/Berlin' },
  { label: '(GMT+01:00) Bratislava, Slovakia', value: 'Europe/Bratislava' },
  { label: '(GMT+01:00) Brussels, Belgium', value: 'Europe/Brussels' },
  { label: '(GMT+01:00) Budapest, Hungary', value: 'Europe/Budapest' },
  { label: '(GMT+01:00) Busingen, Germany', value: 'Europe/Busingen' },
  { label: '(GMT+01:00) Ceuta, Spain', value: 'Africa/Ceuta' },
  { label: '(GMT+01:00) Copenhagen, Denmark', value: 'Europe/Copenhagen' },
  { label: '(GMT+01:00) Gibraltar, Gibraltar', value: 'Europe/Gibraltar' },
  { label: '(GMT+01:00) Kinshasa, DR Congo', value: 'Africa/Kinshasa' },
  { label: '(GMT+01:00) Lagos, Nigeria', value: 'Africa/Lagos' },
  { label: '(GMT+01:00) Libreville, Gabon', value: 'Africa/Libreville' },
  { label: '(GMT+01:00) Luanda, Angola', value: 'Africa/Luanda' },
  { label: '(GMT+01:00) Luxembourg, Luxembourg', value: 'Europe/Luxembourg' },
  { label: '(GMT+01:00) Madrid, Spain', value: 'Europe/Madrid' },
  { label: '(GMT+01:00) Malta, Malta', value: 'Europe/Malta' },
  { label: '(GMT+01:00) Monaco, Monaco', value: 'Europe/Monaco' },
  { label: '(GMT+01:00) Ndjamena, Chad', value: 'Africa/Ndjamena' },
  { label: '(GMT+01:00) Niamey, Niger', value: 'Africa/Niamey' },
  { label: '(GMT+01:00) Oslo, Norway', value: 'Europe/Oslo' },
  { label: '(GMT+01:00) Paris, France', value: 'Europe/Paris' },
  { label: '(GMT+01:00) Podgorica, Montenegro', value: 'Europe/Podgorica' },
  { label: '(GMT+01:00) Prague, Czech Republic', value: 'Europe/Prague' },
  { label: '(GMT+01:00) Rome, Italy', value: 'Europe/Rome' },
  { label: '(GMT+01:00) Stockholm, Sweden', value: 'Europe/Stockholm' },
  { label: '(GMT+01:00) Tunis, Tunisia', value: 'Africa/Tunis' },
  { label: '(GMT+01:00) Vaduz, Liechtenstein', value: 'Europe/Vaduz' },
  { label: '(GMT+01:00) Vienna, Austria', value: 'Europe/Vienna' },
  { label: '(GMT+01:00) Warsaw, Poland', value: 'Europe/Warsaw' },
  { label: '(GMT+01:00) Zagreb, Croatia', value: 'Europe/Zagreb' },
  { label: '(GMT+01:00) Zurich, Switzerland', value: 'Europe/Zurich' },
  { label: '(GMT+03:00) Amman, Jordan', value: 'Asia/Amman' },
  { label: '(GMT+02:00) Athens, Greece', value: 'Europe/Athens' },
  { label: '(GMT+03:00) Beirut, Lebanon', value: 'Asia/Beirut' },
  { label: '(GMT+02:00) Blantyre, Malawi', value: 'Africa/Blantyre' },
  { label: '(GMT+02:00) Bucharest, Romania', value: 'Europe/Bucharest' },
  { label: '(GMT+02:00) Cairo, Egypt', value: 'Africa/Cairo' },
  { label: '(GMT+02:00) Chisinau, Moldova', value: 'Europe/Chisinau' },
  { label: '(GMT+03:00) Damascus, Syria', value: 'Asia/Damascus' },
  { label: '(GMT+02:00) Gaza, Palestine', value: 'Asia/Gaza' },
  { label: '(GMT+02:00) Harare, Zimbabwe', value: 'Africa/Harare' },
  { label: '(GMT+02:00) Hebron, Palestinian Territories', value: 'Asia/Hebron' },
  { label: '(GMT+02:00) Helsinki, Finland', value: 'Europe/Helsinki' },
  { label: '(GMT+02:00) Jerusalem, Israel', value: 'Asia/Jerusalem' },
  { label: '(GMT+02:00) Juba, South Sudan', value: 'Africa/Juba' },
  { label: '(GMT+02:00) Kigali, Rwanda', value: 'Africa/Kigali' },
  { label: '(GMT+02:00) Kyiv, Ukraine', value: 'Europe/Kyiv' },
  { label: '(GMT+02:00) Maputo, Mozambique', value: 'Africa/Maputo' },
  { label: '(GMT+02:00) Moscow-01 (Kaliningrad), Russia', value: 'Europe/Kaliningrad' },
  { label: '(GMT+02:00) Pretoria, South Africa', value: 'Africa/Johannesburg' },
  { label: '(GMT+02:00) Riga, Latvia', value: 'Europe/Riga' },
  { label: '(GMT+02:00) Sofia, Bulgaria', value: 'Europe/Sofia' },
  { label: '(GMT-04:00) St Barthelemy, Saint Barthélemy', value: 'America/St_Barthelemy' },
  { label: '(GMT+02:00) Sudan Standard Time, Sudan', value: 'Africa/Khartoum' },
  { label: '(GMT+02:00) Tripoli, Libya', value: 'Africa/Tripoli' },
  { label: '(GMT+02:00) Windhoek, Namibia', value: 'Africa/Windhoek' },
  { label: '(GMT+03:00) Addis Ababa, Ethiopia', value: 'Africa/Addis_Ababa' },
  { label: '(GMT+03:00) Antananarivo, Madagascar', value: 'Indian/Antananarivo' },
  { label: '(GMT+04:00) Astrakhan, Russia', value: 'Europe/Astrakhan' },
  { label: '(GMT+03:00) Baghdad, Iraq', value: 'Asia/Baghdad' },
  { label: '(GMT+03:00) Bahrain, Bahrain', value: 'Asia/Qatar' },
  { label: '(GMT+03:00) Dar es Salaam, Tanzania', value: 'Africa/Dar_es_Salaam' },
  { label: '(GMT+03:00) Djibouti, Djibouti', value: 'Africa/Djibouti' },
  { label: '(GMT+04:00) Dubai, United Arab Emirates', value: 'Asia/Dubai' },
  { label: '(GMT+02:00) Famagusta, Cyprus', value: 'Asia/Famagusta' },
  { label: '(GMT+03:00) Istanbul, Turkey', value: 'Europe/Istanbul' },
  { label: '(GMT+03:00) Jeddah, Saudi Arabia', value: 'Asia/Riyadh' },
  { label: '(GMT+03:00) Kampala, Uganda', value: 'Africa/Kampala' },
  { label: '(GMT+09:00) Khandyga, Russia', value: 'Asia/Khandyga' },
  { label: '(GMT+03:00) Kuwait, Kuwait', value: 'Asia/Kuwait' },
  { label: '(GMT+02:00) Lusaka, Zambia', value: 'Africa/Lusaka' },
  { label: '(GMT+03:00) Mayotte, Mayotte', value: 'Indian/Mayotte' },
  { label: '(GMT+03:00) Mogadishu, Somalia', value: 'Africa/Mogadishu' },
  { label: '(GMT+03:00) Nairobi, Kenya', value: 'Africa/Nairobi' },
  { label: '(GMT+03:00) Qatar, Qatar', value: 'Asia/Qatar' },
  { label: '(GMT+03:00) Riyadh, Saudi Arabia', value: 'Asia/Riyadh' },
  { label: '(GMT+03:00) Simferopol, Ukraine', value: 'Europe/Simferopol' },
  { label: '(GMT+03:00) South Sudan (Juba), South Sudan', value: 'Africa/Juba' },
  { label: '(GMT+03:00) Syowa Station, Antarctica', value: 'Antarctica/Syowa' },
  { label: '(GMT+04:00) Tbilisi, Georgia', value: 'Asia/Tbilisi' },
  { label: '(GMT+03:30) Tehran, Iran', value: 'Asia/Tehran' },
  { label: '(GMT+04:00) Ulyanovsk, Russia', value: 'Europe/Ulyanovsk' },
  { label: '(GMT+04:00) Yerevan, Armenia', value: 'Asia/Yerevan' },
  { label: '(GMT+04:00) Abu Dhabi, United Arab Emirates', value: 'Asia/Dubai' },
  { label: '(GMT+05:00) Aqtau, Kazakhstan', value: 'Asia/Aqtau' },
  { label: '(GMT+05:00) Aqtobe, Kazakhstan', value: 'Asia/Aqtobe' },
  { label: '(GMT+04:00) Baku, Azerbaijan', value: 'Asia/Baku' },
  { label: '(GMT+04:00) Izhevsk, Russia', value: 'Europe/Samara' },
  { label: '(GMT+05:00) Karachi, Pakistan', value: 'Asia/Karachi' },
  { label: '(GMT+04:00) Kazan, Russia', value: 'Europe/Samara' },
  { label: '(GMT+03:00) Kuwait, Kuwait', value: 'Asia/Kuwait' },
  { label: '(GMT+04:00) Mauritius, Mauritius', value: 'Indian/Mauritius' },
  { label: '(GMT+04:00) Muscat, Oman', value: 'Asia/Dubai' },
  { label: '(GMT+04:00) Reunion, Réunion', value: 'Indian/Reunion' },
  { label: '(GMT+04:00) Samara, Russia', value: 'Europe/Samara' },
  { label: '(GMT+04:00) Saratov, Russia', value: 'Europe/Saratov' },
  { label: '(GMT+04:00) Seychelles, Seychelles', value: 'Indian/Mahe' },
  { label: '(GMT+05:00) Tashkent, Uzbekistan', value: 'Asia/Tashkent' },
  { label: '(GMT+06:00) Oral, Kazakhstan', value: 'Asia/Oral' },
  { label: '(GMT+05:00) Qyzylorda, Kazakhstan', value: 'Asia/Qyzylorda' },
  { label: '(GMT+05:00) Atyrau, Kazakhstan', value: 'Asia/Atyrau' },
  { label: '(GMT+05:00) Ashgabat, Turkmenistan', value: 'Asia/Ashgabat' },
  { label: '(GMT+05:00) Dushanbe, Tajikistan', value: 'Asia/Dushanbe' },
  { label: '(GMT+05:00) Kerguelen, French Southern Territories', value: 'Indian/Kerguelen' },
  { label: '(GMT+05:00) Maldives, Maldives', value: 'Indian/Maldives' },
  { label: '(GMT+05:00) Mawson, Antarctica', value: 'Antarctica/Mawson' },
  { label: '(GMT+05:00) Oral, Kazakhstan', value: 'Asia/Oral' },
  { label: '(GMT+05:00) Pakistan (West), Pakistan', value: 'Asia/Karachi' },
  { label: '(GMT+05:00) Qyzylorda, Kazakhstan', value: 'Asia/Qyzylorda' },
  { label: '(GMT+05:00) Tashkent, Uzbekistan', value: 'Asia/Tashkent' },
  { label: '(GMT+05:00) Yekaterinburg, Russia', value: 'Asia/Yekaterinburg' },
  { label: '(GMT+05:30) Colombo, Sri Lanka', value: 'Asia/Colombo' },
  { label: '(GMT+05:30) Kolkata, India', value: 'Asia/Kolkata' },
  { label: '(GMT+05:45) Kathmandu, Nepal', value: 'Asia/Kathmandu' },
  { label: '(GMT+05:45) Kathmandu, Nepal', value: 'Asia/Kathmandu' },
  { label: '(GMT+06:00) Almaty, Kazakhstan', value: 'Asia/Almaty' },
  { label: '(GMT+06:00) Bishkek, Kyrgyzstan', value: 'Asia/Bishkek' },
  { label: '(GMT+06:00) Chagos, British Indian Ocean Territory', value: 'Indian/Chagos' },
  { label: '(GMT+06:00) Dhaka, Bangladesh', value: 'Asia/Dhaka' },
  { label: '(GMT+06:00) Omsk, Russia', value: 'Asia/Omsk' },
  { label: '(GMT+06:00) Thimphu, Bhutan', value: 'Asia/Thimphu' },
  { label: '(GMT+06:30) Yangon, Myanmar', value: 'Asia/Yangon' },
  { label: '(GMT+07:00) Bangkok, Thailand', value: 'Asia/Bangkok' },
  { label: '(GMT+07:00) Barnaul, Russia', value: 'Asia/Barnaul' },
  { label: '(GMT+07:00) Christmas Island, Australia', value: 'Indian/Christmas' },
  { label: '(GMT+07:00) Davis, Antarctica', value: 'Antarctica/Davis' },
  { label: '(GMT+07:00) Ho Chi Minh, Vietnam', value: 'Asia/Ho_Chi_Minh' },
  { label: '(GMT+07:00) Hovd, Mongolia', value: 'Asia/Hovd' },
  { label: '(GMT+07:00) Jakarta, Indonesia', value: 'Asia/Jakarta' },
  { label: '(GMT+07:00) Krasnoyarsk, Russia', value: 'Asia/Krasnoyarsk' },
  { label: '(GMT+07:00) Novokuznetsk, Russia', value: 'Asia/Novokuznetsk' },
  { label: '(GMT+07:00) Novosibirsk, Russia', value: 'Asia/Novosibirsk' },
  { label: '(GMT+07:00) Phnom Penh, Cambodia', value: 'Asia/Phnom_Penh' },
  { label: '(GMT+07:00) Pontianak, Indonesia', value: 'Asia/Pontianak' },
  { label: '(GMT+07:00) Tomsk, Russia', value: 'Asia/Tomsk' },
  { label: '(GMT+07:00) Vientiane, Laos', value: 'Asia/Vientiane' },
  { label: '(GMT+10:00) Vladivostok- (Oymyakonsky), Russia', value: 'Asia/Ust-Nera' },
  { label: '(GMT+07:00) Western Indonesia (WIB), Indonesia', value: 'Asia/Jakarta' },
  { label: '(GMT+08:00) Brunei, Brunei', value: 'Asia/Brunei' },
  { label: '(GMT+08:00) Beijing, China', value: 'Asia/Shanghai' },
  { label: '(GMT+08:00) Central Indonesia (WITA), Indonesia', value: 'Asia/Makassar' },
  { label: '(GMT+08:00) Choibalsan, Mongolia', value: 'Asia/Choibalsan' },
  { label: '(GMT+12:00) Chukotka, Russia', value: 'Asia/Anadyr' },
  { label: '(GMT+08:00) Hong Kong, Hong Kong', value: 'Asia/Hong_Kong' },
  { label: '(GMT+08:00) Irkutsk, Russia', value: 'Asia/Irkutsk' },
  { label: '(GMT+08:00) Kuala Lumpur, Malaysia', value: 'Asia/Kuala_Lumpur' },
  { label: '(GMT+08:00) Kuching, Malaysia', value: 'Asia/Kuching' },
  { label: '(GMT+08:00) Macau, Macao', value: 'Asia/Macau' },
  { label: '(GMT+08:00) Makassar, Indonesia', value: 'Asia/Makassar' },
  { label: '(GMT+08:00) Manila, Philippines', value: 'Asia/Manila' },
  { label: '(GMT+08:00) Perth, Australia', value: 'Australia/Perth' },
  { label: '(GMT+08:00) Singapore, Singapore', value: 'Asia/Singapore' },
  { label: '(GMT+08:00) Taipei, Taiwan', value: 'Asia/Taipei' },
  { label: '(GMT+09:00) Palau, Palau', value: 'Pacific/Palau' },
  { label: '(GMT+08:30) Pyongyang, North Korea', value: 'Asia/Pyongyang' },
  { label: '(GMT+08:45) Eucla, Australia', value: 'Australia/Eucla' },
  { label: '(GMT+09:00) Dili, Timor-Leste', value: 'Asia/Dili' },
  { label: '(GMT+09:00) Jayapura, Indonesia', value: 'Asia/Jayapura' },
  { label: '(GMT+09:00) Seoul, South Korea', value: 'Asia/Seoul' },
  { label: '(GMT+09:00) Tokyo, Japan', value: 'Asia/Tokyo' },
  { label: '(GMT+09:00) Vladivostok, Russia', value: 'Asia/Vladivostok' },
  { label: '(GMT+09:30) Adelaide, Australia', value: 'Australia/Adelaide' },
  { label: '(GMT+09:30) Broken Hill, Australia', value: 'Australia/Broken_Hill' },
  { label: '(GMT+09:30) Darwin, Australia', value: 'Australia/Darwin' },
  { label: '(GMT+10:00) Brisbane, Australia', value: 'Australia/Brisbane' },
  { label: '(GMT+10:00) Chamorro Standard Time, Guam', value: 'Pacific/Guam' },
  { label: '(GMT+10:00) Chuuk, Micronesia', value: 'Pacific/Chuuk' },
  { label: '(GMT+10:00) Hobart, Australia', value: 'Australia/Hobart' },
  { label: '(GMT+10:00) Port Moresby, Papua New Guinea', value: 'Pacific/Port_Moresby' },
  { label: '(GMT+10:00) Sydney, Australia', value: 'Australia/Sydney' },
  { label: '(GMT+10:00) Vladivostok, Russia', value: 'Asia/Vladivostok' },
  { label: '(GMT+10:30) Lord Howe Island, Australia', value: 'Australia/Lord_Howe' },
  { label: '(GMT+11:00) Bougainville, Papua New Guinea', value: 'Pacific/Bougainville' },
  { label: '(GMT+11:00) Chokurdakh, Russia', value: 'Asia/Srednekolymsk' },
  { label: '(GMT+11:00) Guadalcanal, Solomon Islands', value: 'Pacific/Guadalcanal' },
  { label: '(GMT+11:00) Magadan, Russia', value: 'Asia/Magadan' },
  { label: '(GMT+11:00) New Caledonia, New Caledonia', value: 'Pacific/Noumea' },
  { label: '(GMT+11:00) Norfolk Island, Norfolk Island', value: 'Pacific/Norfolk' },
  { label: '(GMT+11:00) Sakhalin, Russia', value: 'Asia/Sakhalin' },
  { label: '(GMT+11:00) UTC+11 (Kosrae/Pohnpei), Micronesia', value: 'Pacific/Pohnpei' },
  { label: '(GMT+12:00) Anadyr, Russia', value: 'Asia/Anadyr' },
  { label: '(GMT+12:00) Auckland, New Zealand', value: 'Pacific/Auckland' },
  { label: '(GMT+12:00) Fiji, Fiji', value: 'Pacific/Fiji' },
  { label: '(GMT+12:00) Kamchatka, Russia', value: 'Asia/Kamchatka' },
  { label: '(GMT+12:00) Kwajalein, Marshall Islands', value: 'Pacific/Kwajalein' },
  { label: '(GMT+12:00) Majuro, Marshall Islands', value: 'Pacific/Majuro' },
  { label: '(GMT+12:00) Petropavlovsk-Kamchatski, Russia', value: 'Asia/Kamchatka' },
  { label: '(GMT+12:00) Suva, Fiji', value: 'Pacific/Fiji' },
  { label: '(GMT+12:00) Wake, United States Minor Outlying Islands', value: 'Pacific/Wake' },
  { label: '(GMT+12:45) Chatham, New Zealand', value: 'Pacific/Chatham' },
  { label: '(GMT+13:00) Apia, Samoa', value: 'Pacific/Apia' },
  { label: '(GMT+13:00) Fakaofo, Tokelau', value: 'Pacific/Fakaofo' },
  { label: '(GMT+13:00) Kanton, Kiribati', value: 'Pacific/Kanton' },
  { label: '(GMT+11:00) Noumea, New Caledonia', value: 'Pacific/Noumea' },
  { label: '(GMT+13:00) Tongatapu, Tonga', value: 'Pacific/Tongatapu' },
  { label: '(GMT+14:00) Kiritimati, Kiribati', value: 'Pacific/Kiritimati' },
];

export const getGMTZone = () => {
  const offsetInMinutes = new Date().getTimezoneOffset(); // у хвилинах
  const offsetInHours = -offsetInMinutes / 60; // у годинах зі знаком
  const sign = offsetInHours >= 0 ? '+' : '-';
  const absOffset = Math.abs(offsetInHours);
  const hours = String(Math.floor(absOffset)).padStart(2, '0');
  const minutes = String((absOffset % 1) * 60).padStart(2, '0');

  return `GMT${sign}${hours}:${minutes}`;
};

export const getCurrUserTimezone = zone => {
  const userTimeZone = zone || new Intl.DateTimeFormat().resolvedOptions().timeZone;

  if (userTimeZone === 'Europe/Kiev') return 'Europe/Kyiv';

  return userTimeZone;
};

export default timezones;
