// eslint-disable-next-line import/prefer-default-export
export const AMAZON_LINKS_BY_COUNTRY = {
  US: 'amazon.com',
  CA: 'amazon.ca',
  MX: 'amazon.com.mx',
  BR: 'amazon.com.br',
  GB: 'amazon.co.uk',
  FR: 'amazon.fr',
  IT: 'amazon.it',
  ES: 'amazon.es',
  DE: 'amazon.de',
  NL: 'amazon.nl',
  SE: 'amazon.se',
  PL: 'amazon.pl',
  IN: 'amazon.in',
  AE: 'amazon.ae',
  SA: 'amazon.sa',
  SG: 'amazon.sg',
  JP: 'amazon.co.jp',
  AU: 'amazon.com.au',
};
