export const quoteIdForWidget = {
  BCHBTC: '12',
  XRPBTC: '18',
  BXYUSDC: '19',
  NEOBTC: '23',
  VIDBTC: '2',
  ZRXBTC: '24',
  AIONBTC: '17',
  ICXBTC: '14',
  FTMBTC: '21',
  NRGBTC: '16',
  DASHBTC: '26',
  ETCBTC: '27',
  BATBTC: '13',
  EOSBTC: '11',
  ETHUSDC: '9',
  BXYBTC: '5',
  GOBTC: '3',
  XMRBTC: '4',
  POLYBTC: '8',
  LTCBTC: '1',
  ETHBTC: '15',
  TOMOBTC: '25',
  ZECBTC: '7',
  WAVESBTC: '6',
  BTCUSDC: '22',
  MTLBTC: '20',
};
