export const quoteIdForWidget = {
  LTCBTC: '1',
  VIDBTC: '2',
  GOBTC: '3',
  XMRBTC: '4',
  BXYBTC: '5',
  WAVESBTC: '6',
  ZECBTC: '7',
  POLYBTC: '8',
  ETHUSDC: '9',
  BEAMBTC: '10',
  EOSBTC: '11',
  BCHBTC: '12',
  BATBTC: '13',
  ICXBTC: '14',
  ETHBTC: '15',
  NRGBTC: '16',
  AIONBTC: '17',
  XRPBTC: '18',
  BXYUSDC: '19',
  MTLBTC: '20',
  FTMBTC: '21',
  BTCUSDC: '22',
  NEOBTC: '23',
  ZRXBTC: '24',
  TOMOBTC: '25',
  DASHBTC: '26',
  ETCBTC: '27',
};

export default null;
