export const country = {
    'ru': {
        'AD': 'Андорра',
        'AE': 'Объединенные Арабские Эмираты',
        'AF': 'Афганистан',
        'AG': 'Антигуа и Барбуда',
        'AI': 'Ангилья',
        'AL': 'Албания',
        'AM': 'Армения',
        'AN': 'Антильские острова',
        'AO': 'Ангола',
        'AQ': 'Антарктика',
        'AR': 'Аргентина',
        'AS': 'Американские Самоа',
        'AT': 'Австрия',
        'AU': 'Австралия',
        'AW': 'Аруба',
        'AX': 'Аландские острова',
        'AZ': 'Азербайджан',
        'BA': 'Босния и Герцеговина',
        'BB': 'Барбадос',
        'BD': 'Бангладеш',
        'BE': 'Бельгия',
        'BF': 'Буркина Фасо',
        'BG': 'Болгария',
        'BH': 'Бахрейн',
        'BI': 'Бурунди',
        'BJ': 'Бенин',
        'BL': 'Санкт-Бартельми',
        'BM': 'Бермуды',
        'BN': 'Бруней-Даруссалам',
        'BO': 'Боливия',
        'BR': 'Бразилия',
        'BS': 'Багамы',
        'BT': 'Бутан',
        'BV': 'Буве',
        'BW': 'Ботсвана',
        'BY': 'Беларусь',
        'BZ': 'Белиз',
        'CA': 'Канада',
        'CC': 'Кокосовые острова (Килинг)',
        'CD': 'Демократическая Республика Конго',
        'CF': 'Центрально-Африканская Республика',
        'CG': 'Конго',
        'CH': 'Швейцария',
        'CI': 'Кот-д`Ивуар',
        'CK': 'Острова Кука',
        'CL': 'Чили',
        'CM': 'Камерун',
        'CN': 'Китай',
        'CO': 'Колумбия',
        'CR': 'Коста-Рика',
        'CU': 'Куба',
        'CV': 'Кабо-Верде',
        'CX': 'Остров Рождества',
        'CY': 'Кипр',
        'CZ': 'Чешская Республика',
        'DE': 'Германия',
        'DJ': 'Джибути',
        'DK': 'Дания',
        'DM': 'Доминикана',
        'DO': 'Доминиканская Республика',
        'DZ': 'Алжир',
        'EC': 'Эквадор',
        'EE': 'Эстония',
        'EG': 'Египет',
        'EH': 'Западная Сахара',
        'ER': 'Эритрея',
        'ES': 'Испания',
        'ET': 'Эфиопия',
        'FI': 'Финляндия',
        'FJ': 'Фиджи',
        'FK': 'Фолклендские (Мальвинские) острова',
        'FM': 'Микронезия',
        'FO': 'Фарерские острова',
        'FR': 'Франция',
        'GA': 'Габон',
        'GB': 'Великобритания',
        'GD': 'Гренада',
        'GE': 'Грузия',
        'GF': 'Французская Гвиана',
        'GG': 'Гернси',
        'GH': 'Гана',
        'GI': 'Гибралтар',
        'GL': 'Гренландия',
        'GM': 'Гамбия',
        'GN': 'Гвинея',
        'GP': 'Гваделупе',
        'GQ': 'Экваториальная Гвинея',
        'GR': 'Греция',
        'GS': 'Южная Джорджия и Южные Сандвичевы Острова',
        'GT': 'Гватемале',
        'GU': 'Гуам',
        'GW': 'Гвинея-Биссау',
        'GY': 'Гайана',
        'HK': 'Гонконг',
        'HM': 'Острова Херд и Макдональд',
        'HN': 'Гондурас',
        'HR': 'Хорватия',
        'HT': 'Гаити',
        'HU': 'Венгрия',
        'ID': 'Индонезия',
        'IE': 'Ирландия',
        'IL': 'Израиль',
        'IM': 'Остров Мэн',
        'IN': 'Индия',
        'IO': 'Британская территория в Индийском океане',
        'IQ': 'Ирак',
        'IR': 'Иран',
        'IS': 'Исландия',
        'IT': 'Италия',
        'JE': 'Джерси',
        'JM': 'Ямайка',
        'JO': 'Иордания',
        'JP': 'Япония',
        'KE': 'Кения',
        'KG': 'Киргизстан',
        'KH': 'Камбоджа',
        'KI': 'Кирибати',
        'KM': 'Коморские Острова',
        'KN': 'Сент-Китс и Невис',
        'KP': 'Северная Корея',
        'KR': 'Южная Корея',
        'KV': 'Косово',
        'KW': 'Кувейт',
        'KY': 'Каймановы острова',
        'KZ': 'Казахстан',
        'LA': 'Лаос',
        'LB': 'Ливан',
        'LC': 'Сент-Люсии',
        'LI': 'Лихтенштейн',
        'LK': 'Шри-Ланка',
        'LR': 'Либерия',
        'LS': 'Лесото',
        'LT': 'Литва',
        'LU': 'Люксембург',
        'LV': 'Латвия',
        'LY': 'Ливия',
        'MA': 'Морокко',
        'MC': 'Монако',
        'MD': 'Молдова',
        'ME': 'Черногория',
        'MF': 'Святой Мартин',
        'MG': 'Мадагаскар',
        'MH': 'Маршалловы Острова',
        'MK': 'Македония',
        'ML': 'Мали',
        'MM': 'Мьянма',
        'MN': 'Монголия',
        'MO': 'Макао',
        'MP': 'Северные Марианские острова',
        'MQ': 'Мартиника',
        'MR': 'Мавритания',
        'MS': 'Монтсеррат',
        'MT': 'Мальта',
        'MU': 'Остров Маврикий',
        'MV': 'Мальдивы',
        'MW': 'Малави',
        'MX': 'Мексика',
        'MY': 'Малайзия',
        'MZ': 'Мозамбик',
        'NA': 'Намибия',
        'NC': 'Новая Каледония',
        'NE': 'Нигер',
        'NF': 'Остров Норфолк',
        'NG': 'Нигерия',
        'NI': 'Никарагуа',
        'NL': 'Нидерланды',
        'NO': 'Норвегия',
        'NP': 'Непал',
        'NR': 'Науру',
        'NU': 'Ниуэ',
        'NZ': 'Новая Зеландия',
        'OM': 'Оман',
        'PA': 'Панама',
        'PE': 'Перу',
        'PF': 'Французская Полинезия',
        'PG': 'Папуа Новая Гвинея',
        'PH': 'Филиппины',
        'PK': 'Пакистан',
        'PL': 'Польша',
        'PM': 'Сен-Пьер и Микелон',
        'PN': 'Питкэрн',
        'PR': 'Пуэрто-Рико',
        'PS': 'Палестина',
        'PT': 'Португалия',
        'PW': 'Палау',
        'PY': 'Парагвай',
        'QA': 'Катар',
        'RE': 'Реюньон',
        'RO': 'Румыния',
        'RS': 'Сербия',
        'RU': 'Российская Федерация',
        'RW': 'Руанда',
        'SA': 'Саудовская Аравия',
        'SB': 'Соломоновы острова',
        'SC': 'Сейшеллы',
        'SD': 'Судан',
        'SE': 'Швеция',
        'SG': 'Сингапур',
        'SH': 'Святая Елена',
        'SI': 'Словения',
        'SJ': 'Свалбард и Жан Майен',
        'SK': 'Словакия',
        'SL': 'Сьерра Лион',
        'SM': 'Сан-Марино',
        'SN': 'Сенегал',
        'SO': 'Сомали',
        'SR': 'Суринам',
        'SS': 'Южный Судан',
        'ST': 'Сан-Томе и Принсипи',
        'SV': 'Сальвадор',
        'SW': 'Самоа',
        'SY': 'Сирия',
        'SZ': 'Свазиленд',
        'TC': 'Теркс и Кайкос',
        'TD': 'Чад',
        'TF': 'Французские Южные территории',
        'TG': 'Того',
        'TH': 'Таиланд',
        'TJ': 'Таджикистан',
        'TK': 'Токелау',
        'TL': 'Тимор-Лешти',
        'TM': 'Туркменистан',
        'TN': 'Тунис',
        'TO': 'Тонга',
        'TP': 'Восточный Тимор',
        'TR': 'Турция',
        'TT': 'Тринидад и Тобаго',
        'TV': 'Тувалу',
        'TW': 'Тайвань',
        'TZ': 'Танзания',
        'UA': 'Украина',
        'UG': 'Уганда',
        'UM': 'США Внешние малые острова',
        'US': 'США',
        'UY': 'Уругвай',
        'UZ': 'Узбекистан',
        'VA': 'Ватикан',
        'VC': 'Сент-Винсент и Гренадины',
        'VE': 'Венесуэла',
        'VG': 'Британские Виргинские острова',
        'VI': 'Американские Виргинские острова',
        'VN': 'Вьетнам',
        'VU': 'Вануату',
        'WF': 'Уоллис и Футуна',
        'YE': 'Йемен',
        'YT': 'Майотта',
        'ZA': 'Южная Африка',
        'ZM': 'Замбия',
        'ZW': 'Зимбабве'
    },
    'en': {
        'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AF': 'Afghanistan',
        'AG': 'Antigua and Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AN': 'Netherlands Antilles',
        'AO': 'Angola',
        'AQ': 'Antarctica',
        'AR': 'Argentina',
        'AS': 'American Samoa',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Aland Islands',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia and Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'Saint Barthelemy',
        'BM': 'Bermuda',
        'BN': 'Brunei Darussalam',
        'BO': 'Bolivia',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvet Island',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Cocos (Keeling) Islands',
        'CD': 'Congo, the Democratic Republic',
        'CF': 'Central African Republic',
        'CG': 'Congo',
        'CH': 'Switzerland',
        'CI': 'Ivory Coast',
        'CK': 'Cook Islands',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': 'China',
        'CO': 'Colombia',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CX': 'Christmas Island',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DE': 'Germany',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'DZ': 'Algeria',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypt',
        'EH': 'Western Sahara',
        'ER': 'Eritrea',
        'ES': 'Spain',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Falkland Islands (Malvinas)',
        'FM': 'Micronesia',
        'FO': 'Faroe Islands',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'French Guiana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Equatorial Guinea',
        'GR': 'Greece',
        'GS': 'South Georgia & Sandwich Islands',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong',
        'HM': 'Heard Island & McDonald Islands',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'British Indian Ocean Territory',
        'IQ': 'Iraq',
        'IR': 'Iran, Islamic Republic of',
        'IS': 'Iceland',
        'IT': 'Italy',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Japan',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'Saint Kitts and Nevis',
        'KP': `Korea, Democratic People's Republic`,
        'KR': 'South Korea',
        'KV': 'Kosovo',
        'KW': 'Kuwait',
        'KY': 'Cayman Islands',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libyan Arab Jamahiriya',
        'MA': 'Morocco',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'Saint Martin',
        'MG': 'Madagascar',
        'MH': 'Marshall Islands',
        'MK': 'Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolia',
        'MO': 'Macao',
        'MP': 'Northern Mariana Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Norfolk island',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'French Polynesia',
        'PG': 'Papua New Guinea',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'Saint Pierre & Miquelon',
        'PN': 'Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Palestinian Territory',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Russian Federation',
        'RW': 'Rwanda',
        'SA': 'Saudi Arabia',
        'SB': 'Solomon Islands',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapore',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard and Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'South Sudan',
        'ST': 'Sao Tome and Principe',
        'SV': 'El Salvador',
        'SW': 'Samoa',
        'SY': 'Syrian Arab Republic',
        'SZ': 'Swaziland',
        'TC': 'Turks and Caicos Islands',
        'TD': 'Chad',
        'TF': 'French Southern Territories',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TP': 'East Timor',
        'TR': 'Turkey',
        'TT': 'Trinidad and Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'United States Minor Outlying Islands',
        'US': 'United States of America',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Holy See (Vatican City State)',
        'VC': 'Saint Vincent & Grenadines',
        'VE': 'Venezuela',
        'VG': 'Virgin Islands, British',
        'VI': 'American Virgin Islands',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis and Futuna',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'South Africa',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe'
    },
    'pl': {
        'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AF': 'Afghanistan',
        'AG': 'Antigua and Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AN': 'Netherlands Antilles',
        'AO': 'Angola',
        'AQ': 'Antarctica',
        'AR': 'Argentina',
        'AS': 'American Samoa',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Aland Islands',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia and Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'Saint Barthelemy',
        'BM': 'Bermuda',
        'BN': 'Brunei Darussalam',
        'BO': 'Bolivia',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvet Island',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Cocos (Keeling) Islands',
        'CD': 'Congo, the Democratic Republic',
        'CF': 'Central African Republic',
        'CG': 'Congo',
        'CH': 'Switzerland',
        'CI': 'Ivory Coast',
        'CK': 'Cook Islands',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': 'China',
        'CO': 'Colombia',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CX': 'Christmas Island',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DE': 'Germany',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'DZ': 'Algeria',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypt',
        'EH': 'Western Sahara',
        'ER': 'Eritrea',
        'ES': 'Spain',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Falkland Islands (Malvinas)',
        'FM': 'Micronesia',
        'FO': 'Faroe Islands',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'French Guiana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Equatorial Guinea',
        'GR': 'Greece',
        'GS': 'South Georgia & Sandwich Islands',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong',
        'HM': 'Heard Island & McDonald Islands',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'British Indian Ocean Territory',
        'IQ': 'Iraq',
        'IR': 'Iran, Islamic Republic of',
        'IS': 'Iceland',
        'IT': 'Italy',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Japan',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'Saint Kitts and Nevis',
        'KP': `Korea, Democratic People's Republic`,
        'KR': 'South Korea',
        'KV': 'Kosovo',
        'KW': 'Kuwait',
        'KY': 'Cayman Islands',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libyan Arab Jamahiriya',
        'MA': 'Morocco',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'Saint Martin',
        'MG': 'Madagascar',
        'MH': 'Marshall Islands',
        'MK': 'Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolia',
        'MO': 'Macao',
        'MP': 'Northern Mariana Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Norfolk island',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'French Polynesia',
        'PG': 'Papua New Guinea',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'Saint Pierre & Miquelon',
        'PN': 'Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Palestinian Territory',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Russian Federation',
        'RW': 'Rwanda',
        'SA': 'Saudi Arabia',
        'SB': 'Solomon Islands',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapore',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard and Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'South Sudan',
        'ST': 'Sao Tome and Principe',
        'SV': 'El Salvador',
        'SW': 'Samoa',
        'SY': 'Syrian Arab Republic',
        'SZ': 'Swaziland',
        'TC': 'Turks and Caicos Islands',
        'TD': 'Chad',
        'TF': 'French Southern Territories',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TP': 'East Timor',
        'TR': 'Turkey',
        'TT': 'Trinidad and Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'United States Minor Outlying Islands',
        'US': 'United States of America',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Holy See (Vatican City State)',
        'VC': 'Saint Vincent & Grenadines',
        'VE': 'Venezuela',
        'VG': 'Virgin Islands, British',
        'VI': 'American Virgin Islands',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis and Futuna',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'South Africa',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe'
    },
    'es': {
        'AD': 'Andora',
        'AE': 'Emiratos Árabes Unidos',
        'AF': 'Afganistán',
        'AG': 'Antigua y Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AN': 'Antillas Holandesas',
        'AO': 'Angola',
        'AQ': 'Antártida',
        'AR': 'Argentina',
        'AS': 'Samoa, America',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Islas Aland',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia-Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Bélgica',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrein',
        'BI': 'Barundi',
        'BJ': 'Benin',
        'BL': 'San Bartolomé',
        'BM': 'Bermuda',
        'BN': 'Brunei Darussalam',
        'BO': 'Bolivia',
        'BR': 'Brasil',
        'BS': 'Bahamas',
        'BT': 'Bhután',
        'BV': 'Isla Bouvet',
        'BW': 'Botswana',
        'BY': 'Belarús',
        'BZ': 'Belice',
        'CA': 'Canadá',
        'CC': 'Islas del Coco',
        'CD': 'República Democrática del Congo',
        'CF': 'República Centroafricana',
        'CG': 'República del Congo',
        'CH': 'Suiza',
        'CI': 'Costa de Marfil',
        'CK': 'Islas Cook',
        'CL': 'Chile',
        'CM': 'Camerún',
        'CN': 'China',
        'CO': 'Colombia',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CX': 'Isla de Navidad',
        'CY': 'Chipre',
        'CZ': 'República Checa',
        'DE': 'Alemania',
        'DJ': 'Djibouti',
        'DK': 'Dinamarca',
        'DM': 'Dominica',
        'DO': 'República Dominicana',
        'DZ': 'Algeria',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypto',
        'EH': 'Sahara Occidental',
        'ER': 'Eritrea',
        'ES': 'España',
        'ET': 'Etiopía',
        'FI': 'Finlandia',
        'FJ': 'Fiji',
        'FK': 'Islas Malvinas',
        'FM': 'Micronesia',
        'FO': 'Islas Feroe',
        'FR': 'Francia',
        'GA': 'Gabón',
        'GB': 'Reino Unido',
        'GD': 'Granada',
        'GE': 'Georgia',
        'GF': 'Guayana Francés',
        'GG': 'Guernesey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Groenlandia',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadalupe',
        'GQ': 'Guinea Ecuatorial',
        'GR': 'Grecia',
        'GS': 'Islas Georgias del Sur y Sándwich del Sur',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong',
        'HM': 'Islas Heard Island y McDonald',
        'HN': 'Honduras',
        'HR': 'Croacia',
        'HT': 'Haití',
        'HU': 'Hungría',
        'ID': 'Indonesia',
        'IE': 'Irlanda',
        'IL': 'Israel',
        'IM': 'Isla de Man',
        'IN': 'India',
        'IO': 'Territorio Británico del Océano Índico',
        'IQ': 'Irak',
        'IR': 'Iran',
        'IS': 'Islandia',
        'IT': 'Italia',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordán',
        'JP': 'Japón',
        'KE': 'Kenia',
        'KG': 'Kirguistán',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoras',
        'KN': 'San Cristobal y Nieves',
        'KP': 'Corea, República Popular Democrática',
        'KR': 'Corea del Sur',
        'KV': 'Kosovo',
        'KW': 'Kuwait',
        'KY': 'Islas Caimán',
        'KZ': 'Kazajstán',
        'LA': 'Laos',
        'LB': 'Líbano',
        'LC': 'Santa Lucía',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesoto',
        'LT': 'Lituania',
        'LU': 'Luxemburgo',
        'LV': 'Letonia',
        'LY': 'Libia',
        'MA': 'Marruecos',
        'MC': 'Mónaco',
        'MD': 'Moldavia',
        'ME': 'Montenegro',
        'MF': 'San Martín',
        'MG': 'Madagascar',
        'MH': 'Islas Marshall',
        'MK': 'Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolia',
        'MO': 'Macao',
        'MP': 'Islas Marianas del Norte',
        'MQ': 'Martinica',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauricio',
        'MV': 'Maldivas',
        'MW': 'Malawi',
        'MX': 'Méjico',
        'MY': 'Malasia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'Nueva Caledonia',
        'NE': 'Níger',
        'NF': 'Isla Norfolk',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Países Bajos',
        'NO': 'Noruega',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'nueva Zelandia',
        'OM': 'Omán',
        'PA': 'Panamá',
        'PE': 'Perú',
        'PF': 'Polinesia Francesa',
        'PG': 'Papúa Nueva Guinea',
        'PH': 'Filipinas',
        'PK': 'Pakistán',
        'PL': 'Polonia',
        'PM': 'San Pedro y Miquelón',
        'PN': 'Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Palestina',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunión',
        'RO': 'Rumania',
        'RS': 'Serbia',
        'RU': 'Federación de Rusia',
        'RW': 'Ruanda',
        'SA': 'Arabia Saudita',
        'SB': 'Islas Salomón',
        'SC': 'Seychelles',
        'SD': 'Sudán',
        'SE': 'Suecia',
        'SG': 'Singapur',
        'SH': 'Santa Elena',
        'SI': 'Eslovenia',
        'SJ': 'Svalbard y Jan Mayen',
        'SK': 'Eslovaquia',
        'SL': 'Sierra Leona',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Surinam',
        'SS': 'Sudán del Sur',
        'ST': 'Santo Tomé y Príncipe',
        'SV': 'El Salvador',
        'SW': 'Samoa',
        'SY': 'República Árabe Siria',
        'SZ': 'Swazilandia',
        'TC': 'Turks y Caicos',
        'TD': 'Chad',
        'TF': 'Territorios Franceses del Sur',
        'TG': 'Togo',
        'TH': 'Tailandia',
        'TJ': 'Tayikistán',
        'TK': 'Islas Tokelau',
        'TL': 'Timor Oriental',
        'TM': 'Turkmenistán',
        'TN': 'Túnez',
        'TO': 'Tonga',
        'TP': 'Timor Oriental',
        'TR': 'Turquía',
        'TT': 'Trinidad, Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwán',
        'TZ': 'Tanzania',
        'UA': 'Ucrania',
        'UG': 'Uganda',
        'UM': 'Estados Unidos Islas Menores',
        'US': 'Estados Unidos de America',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistán',
        'VA': 'Ciudad del Vaticano',
        'VC': 'San Vicente y las Granadinas',
        'VE': 'Venezuela',
        'VG': 'Islas Vírgenes Británicas',
        'VI': 'Vírgenes estadounidenses Islas',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis, Futuna',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'Sudáfrica',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe'
    },
    'ar': {
        'AD': 'أندورا',
        'AE': 'الامارات العربية المتحدة',
        'AF': 'أفغانستان',
        'AG': 'أنتيجوا وبربودا',
        'AI': 'أنجويلا',
        'AL': 'ألبانيا',
        'AM': 'أرمينيا',
        'AN': 'جزر الأنتيل الهولندية',
        'AO': 'أنجولا',
        'AQ': 'القطب الجنوبي',
        'AR': 'الأرجنتين',
        'AS': 'ساموا الأمريكية',
        'AT': 'النمسا',
        'AU': 'أستراليا',
        'AW': 'آروبا',
        'AX': 'جزر أولان',
        'AZ': 'أذربيجان',
        'BA': 'البوسنة والهرسك',
        'BB': 'بربادوس',
        'BD': 'بنجلاديش',
        'BE': 'بلجيكا',
        'BF': 'بوركينا فاسو',
        'BG': 'بلغاريا',
        'BH': 'البحرين',
        'BI': 'بوروندي',
        'BJ': 'بنين',
        'BL': 'سان بارتيلمي',
        'BM': 'برمودا',
        'BN': 'بروناي',
        'BO': 'بوليفيا',
        'BR': 'البرازيل',
        'BS': 'الباهاما',
        'BT': 'بوتان',
        'BV': 'جزيرة بوفيه',
        'BW': 'بتسوانا',
        'BY': 'روسيا البيضاء',
        'BZ': 'بليز',
        'CA': 'كندا',
        'CC': 'جزر كوكوس',
        'CD': 'جمهورية كونغو الديمقراطية',
        'CF': 'جمهورية افريقيا الوسطى',
        'CG': 'الكونغو - برازافيل',
        'CH': 'سويسرا',
        'CI': 'ساحل العاج',
        'CK': 'جزر كوك',
        'CL': 'شيلي',
        'CM': 'الكاميرون',
        'CN': 'الصين',
        'CO': 'كولومبيا',
        'CR': 'كوستاريكا',
        'CU': 'كوبا',
        'CV': 'الرأس الأخضر',
        'CX': 'جزيرة الكريسماس',
        'CY': 'قبرص',
        'CZ': 'جمهورية التشيك',
        'DE': 'ألمانيا',
        'DJ': 'جيبوتي',
        'DK': 'الدانمرك',
        'DM': 'دومينيكا',
        'DO': 'جمهورية الدومينيك',
        'DZ': 'الجزائر',
        'EC': 'الاكوادور',
        'EE': 'استونيا',
        'EG': 'مصر',
        'EH': 'الصحراء الغربية',
        'ER': 'اريتريا',
        'ES': 'أسبانيا',
        'ET': 'اثيوبيا',
        'FI': 'فنلندا',
        'FJ': 'فيجي',
        'FK': 'جزر فوكلاند',
        'FM': 'ميكرونيسيا',
        'FO': 'جزر فارو',
        'FR': 'فرنسا',
        'GA': 'الجابون',
        'GB': 'المملكة المتحدة',
        'GD': 'جرينادا',
        'GE': 'جورجيا',
        'GF': 'غويانا الفرنسية',
        'GG': 'غيرنسي',
        'GH': 'غانا',
        'GI': 'جبل طارق',
        'GL': 'غرينلاند',
        'GM': 'غامبيا',
        'GN': 'غينيا',
        'GP': 'جوادلوب',
        'GQ': 'غينيا الاستوائية',
        'GR': 'اليونان',
        'GS': 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
        'GT': 'غواتيمالا',
        'GU': 'غوام',
        'GW': 'غينيا بيساو',
        'GY': 'غيانا',
        'HK': 'هونج كونج الصينية',
        'HM': 'جزيرة هيرد وجزر ماكدونالد',
        'HN': 'هندوراس',
        'HR': 'كرواتيا',
        'HT': 'هايتي',
        'HU': 'المجر',
        'ID': 'اندونيسيا',
        'IE': 'أيرلندا',
        'IL': 'يسرائيل',
        'IM': 'جزيرة مان',
        'IN': 'هند',
        'IO': 'المحيط الهندي البريطاني',
        'IQ': 'العراق',
        'IR': 'ايران',
        'IS': 'أيسلندا',
        'IT': 'ايطاليا',
        'JE': 'جيرسي',
        'JM': 'جامايكا',
        'JO': 'الأردن',
        'JP': 'اليابان',
        'KE': 'كينيا',
        'KG': 'قرغيزستان',
        'KH': 'كمبوديا',
        'KI': 'كيريباتي',
        'KM': 'جزر القمر',
        'KN': 'سانت كيتس ونيفيس',
        'KP': 'كوريا الشمالية',
        'KR': 'كوريا الجنوبية',
        'KV': 'كوسوفو',
        'KW': 'الكويت',
        'KY': 'جزر الكايمن',
        'KZ': 'كازاخستان',
        'LA': 'لاوس',
        'LB': 'لبنان',
        'LC': 'سانت لوسيا',
        'LI': 'ليختنشتاين',
        'LK': 'سريلانكا',
        'LR': 'ليبيريا',
        'LS': 'ليسوتو',
        'LT': 'ليتوانيا',
        'LU': 'لوكسمبورغ',
        'LV': 'لاتفيا',
        'LY': 'ليبيا',
        'MA': 'المغرب',
        'MC': 'موناكو',
        'MD': 'مولدافيا',
        'ME': 'الجبل الأسود',
        'MF': 'سانت مارتين',
        'MG': 'مدغشقر',
        'MH': 'جزر المارشال',
        'MK': 'مقدونيا',
        'ML': 'مالي',
        'MM': 'ميانمار',
        'MN': 'منغوليا',
        'MO': 'ماكاو الصينية',
        'MP': 'جزر ماريانا الشمالية',
        'MQ': 'مارتينيك',
        'MR': 'موريتانيا',
        'MS': 'مونتسرات',
        'MT': 'مالطا',
        'MU': 'موريشيوس',
        'MV': 'جزر الملديف',
        'MW': 'ملاوي',
        'MX': 'المكسيك',
        'MY': 'ماليزيا',
        'MZ': 'موزمبيق',
        'NA': 'ناميبيا',
        'NC': 'كاليدونيا الجديدة',
        'NE': 'النيجر',
        'NF': 'جزيرة نورفوك',
        'NG': 'نيجيريا',
        'NI': 'نيكاراجوا',
        'NL': 'هولندا',
        'NO': 'النرويج',
        'NP': 'نيبال',
        'NR': 'ناورو',
        'NU': 'نيوي',
        'NZ': 'نيوزيلاندا',
        'OM': 'عمان',
        'PA': 'بنما',
        'PE': 'بيرو',
        'PF': 'بولينيزيا الفرنسية',
        'PG': 'بابوا غينيا الجديدة',
        'PH': 'الفيلبين',
        'PK': 'باكستان',
        'PL': 'بولندا',
        'PM': 'سانت بيير وميكولون',
        'PN': 'جزر بيتكيرن',
        'PR': 'بورتوريكو',
        'PS': 'فلسطين',
        'PT': 'البرتغال',
        'PW': 'بالاو',
        'PY': 'باراغواي',
        'QA': 'قطر',
        'RE': 'روينيون',
        'RO': 'رومانيا',
        'RS': 'صربيا',
        'RU': 'روسيا',
        'RW': 'رواندا',
        'SA': 'المملكة العربية السعودية',
        'SB': 'جزر سليمان',
        'SC': 'سيشل',
        'SD': 'السودان',
        'SE': 'السويد',
        'SG': 'سنغافورة',
        'SH': 'سانت هيلينا',
        'SI': 'سلوفينيا',
        'SJ': 'سفالبارد وجان مايان',
        'SK': 'سلوفاكيا',
        'SL': 'سيراليون',
        'SM': 'سان مارينو',
        'SN': 'السنغال',
        'SO': 'الصومال',
        'SR': 'سورينام',
        'SS': 'جنوب السودان',
        'ST': 'ساو تومي وبرينسيبي',
        'SV': 'السلفادور',
        'SW': 'ساموا',
        'SY': 'الجمهورية العربية السورية',
        'SZ': 'سوازيلاند',
        'TC': 'جزر توركس وكايكوس',
        'TD': 'تشاد',
        'TF': 'المقاطعات الجنوبية الفرنسية',
        'TG': 'توجو',
        'TH': 'تايلند',
        'TJ': 'طاجكستان',
        'TK': 'توكيلاو',
        'TL': 'تيمور الشرقية',
        'TM': 'تركمانستان',
        'TN': 'تونس',
        'TO': 'تونجا',
        'TP': 'تيمور الشرقي',
        'TR': 'تركيا',
        'TT': 'ترينيداد وتوباغو',
        'TV': 'توفالو',
        'TW': 'تايوان',
        'TZ': 'تانزانيا',
        'UA': 'أوكرانيا',
        'UG': 'أوغندا',
        'UM': 'جزر الولايات المتحدة البعيدة الصغيرة',
        'US': 'الولايات المتحدة الأمريكية',
        'UY': 'أورغواي',
        'UZ': 'أوزبكستان',
        'VA': 'الفاتيكان',
        'VC': 'سانت فنسنت وغرنادين',
        'VE': 'فنزويلا',
        'VG': 'جزر فرجين البريطانية',
        'VI': 'جزر فرجين الأمريكية',
        'VN': 'فيتنام',
        'VU': 'فانواتو',
        'WF': 'جزر والس وفوتونا',
        'YE': 'اليمن',
        'YT': 'مايوت',
        'ZA': 'جمهورية جنوب افريقيا',
        'ZM': 'زامبيا',
        'ZW': 'زيمبابوي'
    },
    'de': {
        'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AF': 'Afghanistan',
        'AG': 'Antigua and Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AN': 'Netherlands Antilles',
        'AO': 'Angola',
        'AQ': 'Antarctica',
        'AR': 'Argentina',
        'AS': 'American Samoa',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Aland Islands',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia and Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'Saint Barthelemy',
        'BM': 'Bermuda',
        'BN': 'Brunei Darussalam',
        'BO': 'Bolivia',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvet Island',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Cocos (Keeling) Islands',
        'CD': 'Congo, the Democratic Republic',
        'CF': 'Central African Republic',
        'CG': 'Congo',
        'CH': 'Switzerland',
        'CI': 'Ivory Coast',
        'CK': 'Cook Islands',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': 'China',
        'CO': 'Colombia',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CX': 'Christmas Island',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DE': 'Germany',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'DZ': 'Algeria',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypt',
        'EH': 'Western Sahara',
        'ER': 'Eritrea',
        'ES': 'Spain',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Falkland Islands (Malvinas)',
        'FM': 'Micronesia',
        'FO': 'Faroe Islands',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'French Guiana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Equatorial Guinea',
        'GR': 'Greece',
        'GS': 'South Georgia & Sandwich Islands',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong',
        'HM': 'Heard Island & McDonald Islands',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'British Indian Ocean Territory',
        'IQ': 'Iraq',
        'IR': 'Iran, Islamic Republic of',
        'IS': 'Iceland',
        'IT': 'Italy',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Japan',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'Saint Kitts and Nevis',
        'KP': `Korea, Democratic People's Republic`,
        'KR': 'South Korea',
        'KV': 'Kosovo',
        'KW': 'Kuwait',
        'KY': 'Cayman Islands',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libyan Arab Jamahiriya',
        'MA': 'Morocco',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'Saint Martin',
        'MG': 'Madagascar',
        'MH': 'Marshall Islands',
        'MK': 'Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolia',
        'MO': 'Macao',
        'MP': 'Northern Mariana Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Norfolk island',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'French Polynesia',
        'PG': 'Papua New Guinea',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'Saint Pierre & Miquelon',
        'PN': 'Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Palestinian Territory',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Russian Federation',
        'RW': 'Rwanda',
        'SA': 'Saudi Arabia',
        'SB': 'Solomon Islands',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapore',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard and Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'South Sudan',
        'ST': 'Sao Tome and Principe',
        'SV': 'El Salvador',
        'SW': 'Samoa',
        'SY': 'Syrian Arab Republic',
        'SZ': 'Swaziland',
        'TC': 'Turks and Caicos Islands',
        'TD': 'Chad',
        'TF': 'French Southern Territories',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TP': 'East Timor',
        'TR': 'Turkey',
        'TT': 'Trinidad and Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'United States Minor Outlying Islands',
        'US': 'United States of America',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Holy See (Vatican City State)',
        'VC': 'Saint Vincent & Grenadines',
        'VE': 'Venezuela',
        'VG': 'Virgin Islands, British',
        'VI': 'American Virgin Islands',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis and Futuna',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'South Africa',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe'
    },
    'it': {
        'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AF': 'Afghanistan',
        'AG': 'Antigua and Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AN': 'Netherlands Antilles',
        'AO': 'Angola',
        'AQ': 'Antarctica',
        'AR': 'Argentina',
        'AS': 'American Samoa',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Aland Islands',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia and Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'Saint Barthelemy',
        'BM': 'Bermuda',
        'BN': 'Brunei Darussalam',
        'BO': 'Bolivia',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvet Island',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Cocos (Keeling) Islands',
        'CD': 'Congo, the Democratic Republic',
        'CF': 'Central African Republic',
        'CG': 'Congo',
        'CH': 'Switzerland',
        'CI': 'Ivory Coast',
        'CK': 'Cook Islands',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': 'China',
        'CO': 'Colombia',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CX': 'Christmas Island',
        'CY': 'Cyprus',
        'CZ': 'Czech Republic',
        'DE': 'Germany',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'DZ': 'Algeria',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypt',
        'EH': 'Western Sahara',
        'ER': 'Eritrea',
        'ES': 'Spain',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Falkland Islands (Malvinas)',
        'FM': 'Micronesia',
        'FO': 'Faroe Islands',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'French Guiana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Equatorial Guinea',
        'GR': 'Greece',
        'GS': 'South Georgia & Sandwich Islands',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong',
        'HM': 'Heard Island & McDonald Islands',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'British Indian Ocean Territory',
        'IQ': 'Iraq',
        'IR': 'Iran, Islamic Republic of',
        'IS': 'Iceland',
        'IT': 'Italy',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Japan',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'Saint Kitts and Nevis',
        'KP': `Korea, Democratic People's Republic`,
        'KR': 'South Korea',
        'KV': 'Kosovo',
        'KW': 'Kuwait',
        'KY': 'Cayman Islands',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libyan Arab Jamahiriya',
        'MA': 'Morocco',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'Saint Martin',
        'MG': 'Madagascar',
        'MH': 'Marshall Islands',
        'MK': 'Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolia',
        'MO': 'Macao',
        'MP': 'Northern Mariana Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Norfolk island',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'French Polynesia',
        'PG': 'Papua New Guinea',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'Saint Pierre & Miquelon',
        'PN': 'Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Palestinian Territory',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Russian Federation',
        'RW': 'Rwanda',
        'SA': 'Saudi Arabia',
        'SB': 'Solomon Islands',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapore',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard and Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'South Sudan',
        'ST': 'Sao Tome and Principe',
        'SV': 'El Salvador',
        'SW': 'Samoa',
        'SY': 'Syrian Arab Republic',
        'SZ': 'Swaziland',
        'TC': 'Turks and Caicos Islands',
        'TD': 'Chad',
        'TF': 'French Southern Territories',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TP': 'East Timor',
        'TR': 'Turkey',
        'TT': 'Trinidad and Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'United States Minor Outlying Islands',
        'US': 'United States of America',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Holy See (Vatican City State)',
        'VC': 'Saint Vincent & Grenadines',
        'VE': 'Venezuela',
        'VG': 'Virgin Islands, British',
        'VI': 'American Virgin Islands',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis and Futuna',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'South Africa',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe'
    }
};
